name: 'Random RickRoll'
branding:
  icon: 'message-circle'  
  color: 'blue'
description: 'Rick-roll when case test fails.'
#author: 'Emmanuel Chicoine, from Tejasv Sharma'
inputs: 
  GITHUB_TOKEN:
    description: 'Github token of the repository'
    required: false
    default: '${{ github.token }}'
runs:
  using: 'node12'
  main: 'index.js'
